services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Lens\Bundle\ApiBundle\Utils\Api:
        arguments: [ [], null, '%kernel.debug%'] # 0 and 1 to be replaced by bundle extension class

    Lens\Bundle\ApiBundle\Serializer\CircularReferenceHandler: ~

    Lens\Bundle\ApiBundle\Utils\ContextBuilder:
        arguments: ['%kernel.debug%', '@request_stack', '@security.token_storage']

    # Alias
    Lens\Bundle\ApiBundle\Utils\ContextBuilderInterface: '@Lens\Bundle\ApiBundle\Utils\ContextBuilder'

    # Listeners
    Lens\Bundle\ApiBundle\EventListener\OptionsRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 9999 }

    Lens\Bundle\ApiBundle\EventListener\ViewListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view, priority: 9999 }

    Lens\Bundle\ApiBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 9999 }

    Lens\Bundle\ApiBundle\Serializer\Normalizer\ExceptionNormalizer:
        tags:
            - { name: serializer.normalizer }
