# Load lens api bundle services
services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    # Event listeners
    lens.api.subscriber.content_negotiation:
        class: Lens\Bundle\ApiBundle\EventListener\ContentNegotiationSubscriber

    lens.api.subscriber.serialize:
        class: Lens\Bundle\ApiBundle\EventListener\SerializeSubscriber

    lens.api.subscriber.exception:
        class: Lens\Bundle\ApiBundle\EventListener\ExceptionSubscriber

    lens.api.subscriber.cors:
        class: Lens\Bundle\ApiBundle\EventListener\CorsSubscriber

    # Import our default api normalizers.
    lens.api.normalizer.exception:
        class: Lens\Bundle\ApiBundle\Serializer\Normalizers\ExceptionNormalizer

    lens.api.normalizer.link_collection:
        class: Lens\Bundle\ApiBundle\Serializer\Normalizers\LinkCollectionNormalizer

    # Inherited classes (dont tag themselves)
    # Also need container arg
    lens.api.normalizer.api_response:
        class: Lens\Bundle\ApiBundle\Serializer\Normalizers\ApiResponseNormalizer
        tags: [serializer.normalizer]
