# Load lens api bundle services
services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    # Event listeners
    Lens\Bundle\ApiBundle\EventListener\ContentNegotiationSubscriber: ~
    # Lens\Bundle\ApiBundle\EventListener\CorsSubscriber: ~
    Lens\Bundle\ApiBundle\EventListener\SerializeSubscriber: ~
    Lens\Bundle\ApiBundle\EventListener\ExceptionSubscriber: ~

    # Import our default api normalizers.
    Lens\Bundle\ApiBundle\Serializer\Normalizers\ExceptionNormalizer:
        tags:
            - { name: lens_serializer.normalizer, priority: 980 }

    Lens\Bundle\ApiBundle\Serializer\Normalizers\LinkCollectionNormalizer:
        tags:
            - { name: lens_serializer.normalizer, priority: 970 }

    Lens\Bundle\ApiBundle\Serializer\Normalizers\ApiResponseNormalizer:
        tags:
            - { name: lens_serializer.normalizer, priority: 990 }
